# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Fira Code

    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Fira Code

    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Fira Code 
    # Style can be specified to pick a specific face.
    style:  Medium

background_opacity: 0.75
